Locales ['es'] = {
  ['valid_purchase'] = 'validar esta compra?',
  ['yes'] = 'si (<span style="color: green;">$%s</span>)',
  ['no'] = 'no',
  ['helmet'] = 'casco / Gorra',
  ['glasses'] = 'gafas',
  ['mask'] = 'mascara',
  ['ears'] = 'pendientes',
  ['shop'] = '%s tienda',
  ['set_unset'] = 'ponerse / quitarse',
  ['not_enough_money'] = 'no tienes suficiente dinero',
  ['press_access'] = 'presione ~INPUT_CONTEXT~ para acceder al menu',
  ['accessories_blip'] = 'accesorios',
  ['no_ears'] = 'no tienes pendientes',
  ['no_glasses'] = 'no tienes gafas',
  ['no_helmet'] = 'no tienes un casco',
  ['no_mask'] = 'no tienes una mascara',
  ['you_paid'] = 'has pagado ~g~$%s~s~',
}
