Locales['es'] = {
  -- Cloakroom
  ['cloakroom'] = 'Guardarropa',
  ['ems_clothes_civil'] = 'Camiseta',
  ['ems_clothes_ems'] = 'Equipo de ambulancia',
  -- Vehicles
  ['ambulance'] = 'ambulancia',
  ['helicopter_prompt'] = 'presiona ~INPUT_CONTEXT~ para acceder a las ~y~Acciones de Helicoptero~s~.',
  ['helicopter_buy'] = 'Tienda de helicopteros',
  ['helicopter_garage'] = 'abrir garaje',
  ['helicopter_store'] = 'almacenar helicoptero en el garaje',
  ['helicopter_garage_title'] = 'Garaje de Helicopteros',
  ['helicopter_title'] = 'Acciones de Helicoptero',
  ['helicopter_notauthorized'] = 'no estas autorizado a comprar helicopteros.',
  ['garage_prompt'] = 'presione ~INPUT_CONTEXT~ para acceder a las ~y~Acciones de Vehiculo~s~.',
  ['garage_title'] = 'Acciones de Vehiculo',
  ['garage_stored'] = 'almacenado',
  ['garage_notstored'] = 'no esta en el garaje',
  ['garage_storing'] = 'estamos intentando eliminar el vehiculo, este seguro que no haya nadie cerca.',
  ['garage_has_stored'] = 'el vehiculo ha sido almacenado en tu garaje.',
  ['garage_has_notstored'] = 'no hay vehiculos propios cerca.',
  ['garage_notavailable'] = 'tu vehiculo no esta almacenado en tu garaje.',
  ['garage_blocked'] = 'no hay puntos de spawn!',
  ['garage_empty'] = 'no tienes ningun vehiculo en tu garaje.',
  ['garage_released'] = 'tu vehiculo ha sido publicado de tu garaje.',
  ['garage_store_nearby'] = 'no hay vehiculos cerca.',
  ['garage_storeditem'] = 'abrir garaje',
  ['garage_storeitem'] = 'almacenar vehiculo en el garaje',
  ['garage_buyitem'] = 'Vehiculos Tienda',
  ['shop_item'] = '$%s',
  ['vehicleshop_title'] = 'Vehiculos Tienda',
  ['vehicleshop_confirm'] = 'quieres comprar este vehiculo?',
  ['vehicleshop_bought'] = 'has comprado ~y~%s~s~ por ~r~$%s~s~',
  ['vehicleshop_money'] = 'no puedes permitirte ese vehículo',
  ['vehicleshop_awaiting_model'] = 'el vehiculo esta ahora mismo ~g~DOWNLOADING & LOADING~s~ por favor espere',
  ['confirm_no'] = 'no',
  ['confirm_yes'] = 'si',
  -- Action Menu
  ['hospital'] = 'hospital',
  ['revive_inprogress'] = 'reanimación en curso',
  ['revive_complete'] = 'has sido reanimado ~y~%s~s~',
  ['revive_complete_award'] = 'has sido reanimado ~y~%s~s~, ~g~$%s~s~',
  ['heal_inprogress'] = 'estas siendo sanado!',
  ['heal_complete'] = 'has sido sanado ~y~%s~s~',
  ['no_players'] = 'ningún jugador cerca',
  ['no_vehicles'] = 'ningún vehículo cerca',
  ['player_not_unconscious'] = 'n\'estás inconsciente',
  ['player_not_conscious'] = 'ese jugador no esta consciente!',
  -- Boss Menu
  ['boss_actions'] = 'boss Actions',
  -- Misc
  ['invalid_amount'] = '~r~cantidad no válida',
  ['actions_prompt'] = 'presione ~INPUT_CONTEXT~ para acceder a las ~y~Acciones de Ambulancia~s~.',
  ['deposit_amount'] = 'cantidad de fianza depositada',
  ['money_withdraw'] = 'cantidad de fianza retirada',
  ['fast_travel'] = 'presione ~INPUT_CONTEXT~ para viaje rapido.',
  ['open_pharmacy'] = 'presione ~INPUT_CONTEXT~ para abrir la parafarmacia.',
  ['pharmacy_menu_title'] = 'Parafarmacia',
  ['pharmacy_take'] = 'coge <span style="color:blue;">%s</span>',
  ['medikit'] = 'Kit Medico',
  ['bandage'] = 'Venda',
  ['max_item'] = 'Estas llevando suficientes en ti mismo.',
  -- F6 Menu
  ['ems_menu'] = 'ayuda ciudadana',
  ['ems_menu_title'] = 'ambulancia - Ayuda Ciudadana',
  ['ems_menu_revive'] = 'reanimar',
  ['ems_menu_putincar'] = 'meter en el vehículo',
  ['ems_menu_small'] = 'curar pequeñas heridas',
  ['ems_menu_big'] = 'tratar lesiones graves',
  -- Phone
  ['alert_ambulance'] = 'Alerta de ambulancia',
  -- Death
  ['respawn_available_in'] = 'respawn habilitado en ~b~%s minutos %s segundos~s~',
  ['respawn_bleedout_in'] = 'te desangrarás en ~b~%s minutos %s segundos~s~\n',
  ['respawn_bleedout_prompt'] = 'manten [~b~E~s~] para respawnear',
  ['respawn_bleedout_fine'] = 'manten [~b~E~s~] para respawnear por ~g~$%s~s~',
  ['respawn_bleedout_fine_msg'] = 'has pagado ~r~$%s~s~ para respawnear.',
  ['distress_send'] = 'presione [~b~G~s~] enviar señal de socorro',
  ['distress_sent'] = 'señal de socorro ha sido enviada a las unidades en servicio!',
  ['distress_message'] = 'Atención médica requerida: ciudadano inconsciente.!',
  ['combatlog_message'] = 'ha sido forzado a reaparecer porque anteriormente ha dejado el servidor cuando estábas muerto.',
  -- Revive
  ['revive_help'] = 'revivir un jugador',
  -- Item
  ['used_medikit'] = 'has usado ~y~1x~s~ Kit Medico',
  ['used_bandage'] = 'has usado ~y~1x~s~ Venda',
  ['not_enough_medikit'] = 'No tienes ~b~Kit Medico~s~.',
  ['not_enough_bandage'] = 'No tienes ~b~Venda~s~.',
  ['healed'] = 'has sido tratado.',
}
