Locales['es'] = {
  -- Cloakroom
  ['cloakroom'] = 'Taquilla',
  ['citizen_wear'] = 'Ropa civil',
  ['police_wear'] = 'Ropa CNP',
  ['gilet_wear'] = 'chaleco reflectante naranja',
  ['bullet_wear'] = 'chaleco antibalas',
  ['no_outfit'] = 'no hay uniforme que te quede bien!',
  ['open_cloackroom'] = 'Presionar ~INPUT_CONTEXT~ para abrir la taquilla',
  -- Armory
  ['remove_object'] = 'coger objeto',
  ['deposit_object'] = 'depositar objeto',
  ['get_weapon'] = 'Coger arma',
  ['put_weapon'] = 'Depositar arma',
  ['buy_weapons'] = 'Comprar armas',
  ['armory'] = 'Arsenal',
  ['open_armory'] = 'Presionarr ~INPUT_CONTEXT~ para acceder a la armeria',
  ['armory_owned'] = 'en propiedad',
  ['armory_free'] = 'libre',
  ['armory_item'] = '$%s',
  ['armory_weapontitle'] = 'armeria - Comprar arma',
  ['armory_componenttitle'] = 'armeria - Accesorios para armas',
  ['armory_bought'] = 'has comprado ~y~%s~s~ por ~r~$%s~s~',
  ['armory_money'] = 'no puedes permitirte ese arma!',
  ['armory_hascomponent'] = 'ya tienes ese accesorio equipado!',
  ['get_weapon_menu'] = 'armeria - Retirar arma',
  ['put_weapon_menu'] = 'armeria - Depositar arma',
  -- Vehicles
  ['vehicle_menu'] = 'vehiculo',
  ['vehicle_blocked'] = 'todos los puntos de spawn estan ahora mismo bloqueados!',
  ['garage_prompt'] = 'presiona ~INPUT_CONTEXT~ para acceder a las ~y~Acciones de Vehiculo~s~.',
  ['garage_title'] = 'Acciones de vehiculo',
  ['garage_stored'] = 'almacenado',
  ['garage_notstored'] = 'no en el garaje',
  ['garage_storing'] = 'estamos intentando quitar el vehículo, asegúrese de que no haya jugadores alrededor.',
  ['garage_has_stored'] = 'el vehiculo ha sido almacenado en tu garaje',
  ['garage_has_notstored'] = 'no hay vehiculos cercanos propios',
  ['garage_notavailable'] = 'tu vehiculo no esta almacenado en el garaje',
  ['garage_blocked'] = 'no hay puntos de spawn permitidos! Estan bloqueados por otro vehiculo.',
  ['garage_empty'] = 'no tienes vehiculos en tu garaje!',
  ['garage_released'] = 'tu vehiculo ha sido publicado en tu garaje!',
  ['garage_store_nearby'] = 'no hay vehiculos cerca.',
  ['garage_storeditem'] = 'abrir garaje',
  ['garage_storeitem'] = 'almacenar vehiculo en el garaje',
  ['garage_buyitem'] = 'tienda de vehiculos',
  ['helicopter_prompt'] = 'presiona ~INPUT_CONTEXT~ para acceder a las ~y~Acciones de Helicoptero~s~.',
  ['helicopter_notauthorized'] = 'no estas autorizado para comprar helicopteros!',
  ['shop_item'] = '$%s',
  ['vehicleshop_title'] = 'Tienda de vehiculos',
  ['vehicleshop_confirm'] = 'quieres comprar esta licencia?',
  ['vehicleshop_bought'] = 'has comprado ~y~%s~s~ por ~r~$%s~s~',
  ['vehicleshop_money'] = 'no puedes permitirte este vehiculo',
  ['vehicleshop_awaiting_model'] = 'el vehiculo esta ahora mismo ~g~DOWNLOADING & LOADING~s~ por favor espera',
  ['confirm_no'] = 'no',
  ['confirm_yes'] = 'si',
  -- Service
  ['service_max'] = 'no puedes entrar al servicio, maximo de operarios: %s/%s',
  ['service_not'] = 'no has entrado al servicio! Primero tienes que cambiarte!',
  ['service_anonunce'] = 'informacion de servicio',
  ['service_in'] = 'has entrado en servicio, bienvenido!',
  ['service_in_announce'] = 'el operario ~y~%s~s~ ha entrado en servicio!',
  ['service_out'] = 'has terminado tu servicio.',
  ['service_out_announce'] = 'el operario ~y~%s~s~ ha terminado su servicio.',
  -- Action Menu
  ['citizen_interaction'] = 'Interacción ciudadana',
  ['vehicle_interaction'] = 'Interacción vehículo',
  ['object_spawner'] = 'Colocar objetos',

  ['id_card'] = 'Documento de identidad',
  ['search'] = 'Buscar',
  ['handcuff'] = 'Poner/quitar Esposas',
  ['drag'] = 'escoltar',
  ['put_in_vehicle'] = 'Meter en el vehículo',
  ['out_the_vehicle'] = 'Sacar del vehículo',
  ['fine'] = 'Multa',
  ['unpaid_bills'] = 'gestionar facturas sin pagar',
  ['license_check'] = 'gestionar licencia',
  ['license_revoke'] = 'revocar licencia',
  ['license_revoked'] = 'tu ~b~%s~s~ ha sido ~y~revocada~s~!',
  ['licence_you_revoked'] = 'has revocado a ~b~%s~s~ que pertenece a ~y~%s~s~',
  ['no_players_nearby'] = 'no hay jugadores cerca',
  ['being_searched'] = 'estas siendo ~y~buscado~s~ por la ~b~Policia~s~',
  -- Vehicle interaction
  ['vehicle_info'] = 'Información del vehículo',
  ['pick_lock'] = 'Forzar coche',
  ['vehicle_unlocked'] = 'Vehículo desbloqueado~s~',
  ['no_vehicles_nearby'] = 'No hay vehículos cerca',
  ['impound'] = 'confiscar vehiculo',
  ['impound_prompt'] = 'presione ~INPUT_CONTEXT~ para cancelar la ~y~confisca~s~',
  ['impound_canceled'] = 'has cancelado la confisca',
  ['impound_canceled_moved'] = 'la confisca se ha cancelado por que el vehiculo se ha movido.',
  ['impound_successful'] = 'has confiscado el vehiculo',
  ['search_database'] = 'informacion del vehiculo',
  ['search_database_title'] = 'informacion del vehiculo - buscar con numero de registro',
  ['search_database_error_invalid'] = 'ese ~r~no es~s~ un numero de registro ~y~valido~s~',
  ['search_database_error_not_found'] = 'ese ~y~numero de registro~s~ ~r~no esta~s~ registrado a un vehiculo!',
  ['search_database_found'] = 'el vehiculo esta ~y~registrado~s~ a ~b~%s~s~',
  -- Traffic interaction
  ['traffic_interaction'] = 'Rutas de interacción',
  ['cone'] = 'Cono',
  ['barrier'] = 'Barrera',
  ['spikestrips'] = 'Grada',
  ['box'] = 'Caja',
  ['cash'] = 'Dinero',
  -- ID Card Menu
  ['name'] = 'nombre: %s',
  ['job'] = 'trabajo: %s',
  ['sex'] = 'sexo: %s',
  ['dob'] = 'DOB: %s',
  ['height'] = 'altura: %s',
  ['id'] = 'ID: %s',
  ['bac'] = 'BAC: %s',
  ['unknown'] = 'desconocido',
  ['male'] = 'hombre',
  ['female'] = 'mujer',
  -- Body Search Menu
  ['guns_label'] = '--- Armas ---',
  ['inventory_label'] = '--- Inventario ---',
  ['license_label'] = ' --- Licenses ---',
  ['confiscate'] = 'confiscar %s',
  ['confiscate_weapon'] = 'confiscar %s con %s balas',
  ['confiscate_inv'] = 'confiscar %sx %s',
  ['confiscate_dirty'] = 'confiscar dinero negro: <span style="color:red;">€%s</span>',
  ['you_confiscated'] = 'has confiscado ~y~%sx~s~ ~b~%s~s~ de ~b~%s~s~',
  ['got_confiscated'] = '~y~%sx~s~ ~b~%s~s~ fue confiscado por ~y~%s~s~',
  ['you_confiscated_account'] = 'has confiscado ~g~€%s~s~ (%s) de ~b~%s~s~',
  ['got_confiscated_account'] = '~g~€%s~s~ (%s) ha sido confiscado por ~y~%s~s~',
  ['you_confiscated_weapon'] = 'has confiscado ~b~%s~s~ de ~b~%s~s~ con ~o~%s~s~ balas',
  ['got_confiscated_weapon'] = 'tu ~b~%s~s~ con ~o~%s~s~ balas ha sido confiscada por ~y~%s~s~',
  ['traffic_offense'] = 'Delito de tráfico',
  ['minor_offense'] = 'Delito menor',
  ['average_offense'] = 'Delito medio',
  ['major_offense'] = 'Delito grave',
  ['fine_total'] = 'Multa total: %s',
  -- Vehicle Info Menu
  ['plate'] = 'n°: %s',
  ['owner_unknown'] = 'propietario: Desconocido',
  ['owner'] = 'propietario: %s',
  -- Boss Menu
  ['open_bossmenu'] = 'presionar ~INPUT_CONTEXT~ para abrir el menú',
  ['quantity_invalid'] = 'cantidad invalida',
  ['have_withdrawn'] = 'has retirado ~y~%sx~s~ ~b~%s~s~',
  ['have_deposited'] = 'has depositado ~y~%sx~s~ ~b~%s~s~',
  ['quantity'] = 'cantidad',
  ['inventory'] = 'inventario',
  ['police_stock'] = 'almacen Policial',
  -- Misc
  ['remove_prop'] = 'presionar ~INPUT_CONTEXT~ para eliminar el objeto',
  ['map_blip'] = 'comisaría de policía',
  ['unrestrained_timer'] = 'sientes que las esposas pierden agarre lentamente y se desvanecen.',
  -- Notifications
  ['alert_police'] = 'alerta policia',
  ['phone_police'] = 'policia',
}
