Locales['es'] = {
  -- cloakroom
  ['cloakroom_menu'] = 'guardarropa',
  ['cloakroom_prompt'] = 'presione ~INPUT_CONTEXT~ para acceder al ~y~guardarropas~s~.',
  ['wear_citizen'] = 'ropa civil',
  ['wear_work'] = 'ropa trabajador',

  -- garage
  ['spawner_prompt'] = 'presione ~INPUT_CONTEXT~ para acceder al ~y~Garage~s~.',
  ['store_veh'] = 'presione ~INPUT_CONTEXT~ para almacenar el vehiculo.',
  ['spawn_veh'] = 'spawn vehiculo',
  ['spawnpoint_blocked'] = 'hay un vehiculo bloqueando el spawnpoint!',
  ['only_taxi'] = 'solo puedes almacenar taxis!',

  ['taking_service'] = 'cogiendo servicio: Taxi/Uber',
  ['full_service'] = 'sevicio lleno: ',
  ['amount_invalid'] = 'cantidad invalida',
  ['press_to_open'] = 'presione ~INPUT_CONTEXT~ para acceder al menu',
  ['billing'] = 'billing',
  ['billing_sent'] = 'la factura ha sido creada!',
  ['invoice_amount'] = 'invoice amount',
  ['no_players_near'] = 'no hay jugadores cerca',
  ['start_job'] = 'start / stop driving NPC jobs',
  ['drive_search_pass'] = 'driving in search of ~y~passengers',
  ['customer_found'] = 'has ~g~encontrado~s~ un cliente, acercate a el.',
  ['client_unconcious'] = 'tu cliente esta ~r~inconsciente~s~, busca otro!',
  ['arrive_dest'] = 'has ~g~llegado~s~ a tu destino.',
  ['take_me_to_near'] = '~s~llevame a~y~ %s~s~, cerca ~y~%s',
  ['take_me_to'] = '~s~llevame a ~y~%s',
  ['close_to_client'] = 'estas muy lejos del cliente, vuelve más cerca de el',
  ['return_to_veh'] = 'porfavor vuelve a tu vehiculo para continuar la mision',
  ['must_in_taxi'] = 'debes estar en un ~y~taxi~s~ para empezar la mision',
  ['must_in_vehicle'] = 'debes estar en un vehiculo para comenzar la mision',
  ['have_earned'] = 'has ganado ~g~$%s~s~',
  ['comp_earned'] = '- tu compañia ha ganado ~g~$%s~s~\n- tu has ganado ~g~$%s~s~',
  ['deposit_stock'] = 'depositar stock',
  ['take_stock'] = 'coger stock',
  ['boss_actions'] = 'boss Actions',
  ['mission_complete'] = 'mision completa',
  ['quantity'] = 'cantidad',
  ['quantity_invalid'] = 'esta es una cantidad invalida!',
  ['inventory'] = 'inventario',
  ['taxi_client'] = 'cliente taxi',
  ['have_withdrawn'] = 'has retirado ~y~x%s~s~ ~b~%s~s~',
  ['have_deposited'] = 'has depositado ~y~x%s~s~ ~b~%s~s~',
  ['player_cannot_hold'] = 'tu ~r~no~s~ tienes suficiente ~y~espacio libre~s~ en tu inventario!',
  ['blip_taxi'] = 'downtown Cab Co.',
  ['phone_taxi'] = 'downtown Cab Co.',
}